set(_CATKIN_CURRENT_PACKAGE "arm_server")
set(arm_server_VERSION "0.0.0")
set(arm_server_MAINTAINER "sub <sub@todo.todo>")
set(arm_server_PACKAGE_FORMAT "2")
set(arm_server_BUILD_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "tf")
set(arm_server_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "roscpp")
set(arm_server_BUILDTOOL_DEPENDS "catkin")
set(arm_server_BUILDTOOL_EXPORT_DEPENDS )
set(arm_server_EXEC_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "tf")
set(arm_server_RUN_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "tf")
set(arm_server_TEST_DEPENDS )
set(arm_server_DOC_DEPENDS )
set(arm_server_URL_WEBSITE "")
set(arm_server_URL_BUGTRACKER "")
set(arm_server_URL_REPOSITORY "")
set(arm_server_DEPRECATED "")