set(_CATKIN_CURRENT_PACKAGE "elevator")
set(elevator_VERSION "0.0.0")
set(elevator_MAINTAINER "Omri Eitan <omrieitan@gmail.com>")
set(elevator_PACKAGE_FORMAT "2")
set(elevator_BUILD_DEPENDS "roscpp" "rospy" "actionlib" "actionlib_msgs" "std_msgs" "tf")
set(elevator_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "actionlib_msgs")
set(elevator_BUILDTOOL_DEPENDS "catkin")
set(elevator_BUILDTOOL_EXPORT_DEPENDS )
set(elevator_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "actionlib_msgs" "tf")
set(elevator_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "actionlib_msgs" "tf")
set(elevator_TEST_DEPENDS )
set(elevator_DOC_DEPENDS )
set(elevator_URL_WEBSITE "")
set(elevator_URL_BUGTRACKER "")
set(elevator_URL_REPOSITORY "")
set(elevator_DEPRECATED "")