set(_CATKIN_CURRENT_PACKAGE "generate_srv")
set(generate_srv_VERSION "0.0.0")
set(generate_srv_MAINTAINER "tal <tal@todo.todo>")
set(generate_srv_PACKAGE_FORMAT "2")
set(generate_srv_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(generate_srv_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(generate_srv_BUILDTOOL_DEPENDS "catkin")
set(generate_srv_BUILDTOOL_EXPORT_DEPENDS )
set(generate_srv_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(generate_srv_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(generate_srv_TEST_DEPENDS )
set(generate_srv_DOC_DEPENDS )
set(generate_srv_URL_WEBSITE "")
set(generate_srv_URL_BUGTRACKER "")
set(generate_srv_URL_REPOSITORY "")
set(generate_srv_DEPRECATED "")