set(_CATKIN_CURRENT_PACKAGE "robotican_demos_upgrade")
set(robotican_demos_upgrade_VERSION "0.0.0")
set(robotican_demos_upgrade_MAINTAINER "yam <yam@todo.todo>")
set(robotican_demos_upgrade_PACKAGE_FORMAT "1")
set(robotican_demos_upgrade_BUILD_DEPENDS "generate_srv" "roscpp" "rospy" "std_msgs" "move_base_msgs" "actionlib" "cv_bridge" "pcl_conversions" "pcl_ros" "moveit_core" "moveit_ros_planning" "moveit_ros_planning_interface" "tf" "moveit_msgs" "moveit_core" "moveit_ros_planning_interface" "message_generation")
set(robotican_demos_upgrade_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "move_base_msgs" "actionlib" "generate_srv" "cv_bridge" "pcl_conversions" "pcl_ros" "moveit_core" "moveit_ros_planning" "moveit_ros_planning_interface" "tf" "moveit_msgs" "moveit_core" "moveit_ros_planning_interface" "message_runtime")
set(robotican_demos_upgrade_BUILDTOOL_DEPENDS "catkin")
set(robotican_demos_upgrade_BUILDTOOL_EXPORT_DEPENDS )
set(robotican_demos_upgrade_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "move_base_msgs" "actionlib" "generate_srv" "cv_bridge" "pcl_conversions" "pcl_ros" "moveit_core" "moveit_ros_planning" "moveit_ros_planning_interface" "tf" "moveit_msgs" "moveit_core" "moveit_ros_planning_interface" "message_runtime")
set(robotican_demos_upgrade_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "move_base_msgs" "actionlib" "generate_srv" "cv_bridge" "pcl_conversions" "pcl_ros" "moveit_core" "moveit_ros_planning" "moveit_ros_planning_interface" "tf" "moveit_msgs" "message_runtime")
set(robotican_demos_upgrade_TEST_DEPENDS )
set(robotican_demos_upgrade_DOC_DEPENDS )
set(robotican_demos_upgrade_URL_WEBSITE "")
set(robotican_demos_upgrade_URL_BUGTRACKER "")
set(robotican_demos_upgrade_URL_REPOSITORY "")
set(robotican_demos_upgrade_DEPRECATED "")