# CMake generated Testfile for 
# Source directory: /home/lab16/catkin_ws/src
# Build directory: /home/lab16/catkin_ws/src/librealsense-2.10.3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(gtest)
subdirs(armadillo/armadillo2_description)
subdirs(armadillo/armadillo2_moveit_config)
subdirs(armadillo/armadillo2_navigation)
subdirs(armadillo/armadillo2_utils/iai_kinect2/iai_kinect2)
subdirs(armadillo/armadillo2_utils/intel_d435)
subdirs(armadillo/armadillo2_utils/ros_twist_mux)
subdirs(armadillo/armadillo2_msgs)
subdirs(armadillo/armadillo2_services)
subdirs(armadillo/armadillo2_utils/bms_interface)
subdirs(armadillo/armadillo2_utils/dynamixel_sdk)
subdirs(armadillo/armadillo2_utils/dxl_interface)
subdirs(armadillo/armadillo2_utils/filters)
subdirs(generate_srv)
subdirs(armadillo/armadillo2)
subdirs(armadillo/armadillo2_control)
subdirs(test)
subdirs(armadillo/armadillo2_utils/espeak_ros)
subdirs(armadillo/armadillo2_utils/iai_kinect2/kinect2_registration)
subdirs(manipulator_servers/arm_server)
subdirs(OmerArmadillo2)
subdirs(manipulator_servers/client_demo)
subdirs(elevator)
subdirs(armadillo/armadillo2_gazebo)
subdirs(armadillo/armadillo2_utils/iai_kinect2/kinect2_bridge)
subdirs(armadillo/armadillo2_utils/iai_kinect2/kinect2_calibration)
subdirs(armadillo/armadillo2_utils/iai_kinect2/kinect2_viewer)
subdirs(realsense-ros-2.0.3/realsense2_camera)
subdirs(armadillo/armadillo2_sim_interface)
subdirs(armadillo/armadillo2_utils/roboteq_control)
subdirs(armadillo/armadillo2_utils/urg_node)
subdirs(armadillo/armadillo2_teleop)
subdirs(armadillo/armadillo2_demos/object_detection)
subdirs(robotican_demos_upgrade)
subdirs(armadillo/armadillo2_hw)
subdirs(armadillo/armadillo2_controllers/gripper_action_controller)
subdirs(armadillo/armadillo2_controllers/joint_trajectory_controller)
