set(_CATKIN_CURRENT_PACKAGE "client_demo")
set(client_demo_VERSION "0.0.0")
set(client_demo_MAINTAINER "sub <sub@todo.todo>")
set(client_demo_PACKAGE_FORMAT "2")
set(client_demo_BUILD_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "arm_server")
set(client_demo_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "arm_server")
set(client_demo_BUILDTOOL_DEPENDS "catkin")
set(client_demo_BUILDTOOL_EXPORT_DEPENDS )
set(client_demo_EXEC_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "arm_server")
set(client_demo_RUN_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "arm_server")
set(client_demo_TEST_DEPENDS )
set(client_demo_DOC_DEPENDS )
set(client_demo_URL_WEBSITE "")
set(client_demo_URL_BUGTRACKER "")
set(client_demo_URL_REPOSITORY "")
set(client_demo_DEPRECATED "")