set(_CATKIN_CURRENT_PACKAGE "intel_d435")
set(intel_d435_VERSION "0.0.0")
set(intel_d435_MAINTAINER "sub <sub@todo.todo>")
set(intel_d435_PACKAGE_FORMAT "2")
set(intel_d435_BUILD_DEPENDS )
set(intel_d435_BUILD_EXPORT_DEPENDS )
set(intel_d435_BUILDTOOL_DEPENDS "catkin")
set(intel_d435_BUILDTOOL_EXPORT_DEPENDS )
set(intel_d435_EXEC_DEPENDS )
set(intel_d435_RUN_DEPENDS )
set(intel_d435_TEST_DEPENDS )
set(intel_d435_DOC_DEPENDS )
set(intel_d435_URL_WEBSITE "")
set(intel_d435_URL_BUGTRACKER "")
set(intel_d435_URL_REPOSITORY "")
set(intel_d435_DEPRECATED "")