# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickAction.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickActionGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickActionResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickActionFeedback.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePickFeedback.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceAction.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceActionGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceActionResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceActionFeedback.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimplePlaceFeedback.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetAction.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetActionGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetActionResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetActionFeedback.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetGoal.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetResult.msg;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg/SimpleTargetFeedback.msg"
services_str = ""
pkg_name = "arm_server"
dependencies_str = "actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "arm_server;/home/lab16/catkin_ws/src/librealsense-2.10.3/devel/share/arm_server/msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
