set(_CATKIN_CURRENT_PACKAGE "armadillo2_bgu")
set(armadillo2_bgu_VERSION "0.0.0")
set(armadillo2_bgu_MAINTAINER "armadillo2 <armadillo2@todo.todo>")
set(armadillo2_bgu_PACKAGE_FORMAT "2")
set(armadillo2_bgu_BUILD_DEPENDS "roscpp" "std_msgs" "tf" "actionlib" "actionlib_msgs" "message_generation")
set(armadillo2_bgu_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(armadillo2_bgu_BUILDTOOL_DEPENDS "catkin")
set(armadillo2_bgu_BUILDTOOL_EXPORT_DEPENDS )
set(armadillo2_bgu_EXEC_DEPENDS "roscpp" "std_msgs" "message_generation" "actionlib" "actionlib_msgs" "message_runtime")
set(armadillo2_bgu_RUN_DEPENDS "roscpp" "std_msgs" "message_generation" "actionlib" "actionlib_msgs" "message_runtime")
set(armadillo2_bgu_TEST_DEPENDS )
set(armadillo2_bgu_DOC_DEPENDS )
set(armadillo2_bgu_URL_WEBSITE "")
set(armadillo2_bgu_URL_BUGTRACKER "")
set(armadillo2_bgu_URL_REPOSITORY "")
set(armadillo2_bgu_DEPRECATED "")